name = "Link"
# The minimum version of Zola required
min_version = "0.11.0"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
date_format = "%e %B %Y"
links = []

